siteTitle="Smooch Docs"

[sections.guide]
subsections = [
    'home',
    'authentication',
    'programmable-messaging',
    'users',
    'managed-accounts',
    'smooch-connect',
    'channels',
    'built-in-integrations',
    'references'
]

[sections.api]
subsections = [
    'rest'
]

[sections.faq]
subsections = [
    'faq',
    'customer-channels',
    'business-systems',
    'dashboard'
]

[subsections.home]
name = "Home"
pages = [
    "/guide/",
    "/guide/api-quickstart/",
    "/guide/business-quickstart/"
]

[subsections.authentication]
name = "Accessing the Smooch API"
pages = [
    "/guide/authorization/",
    "/guide/jwt/",
    "/guide/authenticating-to-smooch-api/"
]

[subsections.programmable-messaging]
name = "Programmable Conversations"
pages = [
    "/guide/receiving-messages/",
    "/guide/sending-messages/",
    "/guide/structured-messages/"
]

[subsections.users]
name = "Users"
pages = [
    "/guide/managing-user-information/",
    "/guide/authenticating-users/",
    "/guide/creating-users/",
    "/guide/linking-users-to-sms/",
    "/guide/multi-device-users/"
]

[subsections.managed-accounts]
name = "Managed Accounts"
pages = [
    "/guide/intro-to-managed-accounts/",
    "/guide/creating-and-managing-apps/",
    "/guide/configuring-messaging-channels/",
]

[subsections.smooch-connect]
name = "Smooch Connect"
pages = [
    "/guide/intro-to-smooch-connect/",
    "/guide/oauth/",
    "/guide/becoming-an-integration-partner/",
]

[subsections.channels]
name = "Channels"
pages = [
    "/guide/ott-messengers/",
    "/guide/sms/",
    "/guide/email/",
    "/guide/web-messenger/",
    "/guide/native-ios-sdk/",
    "/guide/native-android-sdk/",
    "/guide/channel-capabilities/"
]

[subsections.built-in-integrations]
name = "Built-in Integrations"
pages = [
    "/guide/configuring-business-systems/",
    "/guide/stripe-payments/",
    "/guide/automated-messages/",
    "/guide/office-hours/"
]

[subsections.references]
name = "References"
pages = [
    "API Reference__https://docs.smooch.io/rest/",
    "/faq/",
    "/guide/error-messages/",
    "/changelog/",
    "Webhook Payload Spec__http://docs.smooch.io/rest/#webhooks-payload",
    "/guide/security/",
    "/guide/sending-images-and-buttons-shorthand/"
]

[subsections.rest]
name = "REST"
pages = [
    "/api/",
    "/api/connect/",
    "/api/inside/"
]

[subsections.faq]
name = "Frequently Asked Questions (FAQ)"
pages = [
    "Welcome__/faq/"
]

[subsections.customer-channels]
name = "Channels"
pages = [
    "/faq/android/",
    "/faq/ios/",
    "/faq/web-messenger/",
    "/faq/facebook-messenger/",
    "/faq/twilio/",
    "/faq/other-channels/"
]

[subsections.business-systems]
name = "Business Systems"
pages = [
    "/faq/slack/",
    "/faq/front/",
    "/faq/other-systems/"
]

[subsections.dashboard]
name = "Dashboard"
pages = [
  "/faq/dashboard/",
  "/faq/whispers/"
]
