siteTitle="Smooch Docs"

[sections.docs]
subsections = [
    'home',
    'authentication',
    'programmable-messaging',
    'users',
    'managed-accounts',
    'smooch-connect',
    'channels',
    'built-in-integrations',
    'references'
]

[sections.api]
subsections = [
    'rest'
]

[sections.faq]
subsections = [
    'faq',
    'customer-channels',
    'business-systems',
    'pricing-and-legal',
    'dashboard'
]

[subsections.home]
name = "Home"
pages = [
    "/docs/",
    "/docs/api-quickstart/",
    "/docs/business-quickstart/"
]

[subsections.authentication]
name = "Accessing the Smooch API"
pages = [
    "/docs/authorization/",
    "/docs/jwt/",
    "/docs/authenticating-to-smooch-api/"
]

[subsections.programmable-messaging]
name = "Programmable Conversations"
pages = [
    "/docs/receiving-messages/",
    "/docs/sending-messages/",
    "/docs/structured-messages/"
]

[subsections.users]
name = "Users"
pages = [
    "/docs/managing-user-information/",
    "/docs/authenticating-users/",
    "/docs/creating-users/",
    "/docs/linking-users-to-sms/"
]

[subsections.managed-accounts]
name = "Managed Accounts"
pages = [
    "/docs/intro-to-managed-accounts/",
    "/docs/creating-and-managing-apps/",
    "/docs/configuring-messaging-channels/",
]

[subsections.smooch-connect]
name = "Smooch Connect"
pages = [
    "/docs/intro-to-smooch-connect/",
    "/docs/oauth/",
    "/docs/becoming-an-integration-partner/",
]

[subsections.channels]
name = "Channels"
pages = [
    "/docs/native-sdks/",
    "/docs/ott-messenger/",
    "/docs/email/",
    "/docs/channel-capabilities/"
]

[subsections.built-in-integrations]
name = "Built-in Integrations"
pages = [
    "/docs/configuring-business-systems/",
    "/docs/stripe-payments/",
    "/docs/automated-messages/",
    "/docs/office-hours/"
]

[subsections.references]
name = "References"
pages = [
    "API Reference__https://docs.smooch.io/rest/",
    "Frequently Asked Questions (FAQ)__/faq/",
    "/docs/error-messages/",
    "/changelog/",
    "/docs/webhooks-specs/",
    "/docs/security/",
    "/docs/technical-info/",
    "/docs/sending-images-and-buttons-shorthand/",
]

[subsections.rest]
name = "REST"
pages = [
    "/api/",
    "/api/connect/",
    "/api/inside/"
]

[subsections.faq]
name = "Frequently Asked Questions (FAQ)"
pages = [
    "/faq/"
]

[subsections.customer-channels]
name = "Channels"
pages = [
    "/faq/android/",
    "/faq/ios/",
    "/faq/web-messenger/",
    "/faq/facebook-messenger/",
    "/faq/twilio/",
    "/faq/other-channels/"
]

[subsections.business-systems]
name = "Business Systems"
pages = [
    "/faq/slack/",
    "/faq/front/",
    "/faq/other-systems/"
]

[subsections.pricing-and-legal]
name = "Pricing & Legal"
pages = [
    "/faq/pricing/",
    "/faq/legal/"
]

[subsections.dashboard]
name = "Dashboard"
pages = [
  "/faq/dashboard/",
  "/faq/whispers/"
]
