siteTitle="Smooch Docs"

[sections.docs]
subsections = [
    'home',
    'authentication',
    'programmable-messaging',
    'users',
    'managed-accounts',
    'smooch-connect',
    'channels',
    'built-in-integrations',
    'references'
]

[sections.api]
subsections = [
    'rest'
]

[subsections.home]
name = "Home"
pages = [
    "/docs/",
    "/docs/api-quickstart/",
    "/docs/business-quickstart/"
]

[subsections.authentication]
name = "Accessing the Smooch API"
pages = [
    "/docs/authorization/",
    "/docs/jwt/",
    "/docs/authenticating-to-smooch-api/"
]

[subsections.programmable-messaging]
name = "Programmable Conversations"
pages = [
    "/docs/receiving-messages/",
    "/docs/sending-messages/",
    "/docs/structured-messages/"
]

[subsections.users]
name = "Users"
pages = [
    "/docs/managing-user-information/",
    "/docs/authenticating-users/",
    "/docs/creating-users/",
    "/docs/linking-users-to-sms/",
    "/docs/multi-device-users/"
]

[subsections.managed-accounts]
name = "Managed Accounts"
pages = [
    "/docs/intro-to-managed-accounts/",
    "/docs/creating-and-managing-apps/",
    "/docs/configuring-messaging-channels/",
]

[subsections.smooch-connect]
name = "Smooch Connect"
pages = [
    "/docs/intro-to-smooch-connect/",
    "/docs/oauth/",
    "/docs/becoming-an-integration-partner/",
]

[subsections.channels]
name = "Channels"
pages = [
    "/docs/ott-messengers/",
    "/docs/sms/",
    "/docs/email/",
    "/docs/web-messenger/",
    "/docs/native-ios-sdk/",
    "/docs/native-android-sdk/",
    "/docs/channel-capabilities/"
]

[subsections.built-in-integrations]
name = "Built-in Integrations"
pages = [
    "/docs/configuring-business-systems/",
    "/docs/stripe-payments/",
    "/docs/automated-messages/",
    "/docs/office-hours/"
]

[subsections.references]
name = "References"
pages = [
    "API Reference__https://docs.smooch.io/rest/",
    "/changelog/",
    "Webhook Payload Spec__http://docs.smooch.io/rest/#webhooks-payload",
    "/docs/security/",
    "/docs/faq/",
    "/docs/sending-images-and-buttons-shorthand/",
]

[subsections.rest]
name = "REST"
pages = [
    "/api/",
    "/api/connect/",
    "/api/inside/"
]
